/*
   I could not able to execute the pipeline due to infrastructure issues,
   but I came up with Jenkinsfile such a way that with minimum updates,
   we can build the pipeline in Jenkins.
*/

def repo_url = "git@github.com:maheshglm/blockone.git"

pipeline {

    //Assume we have an agent configured with Java11, Maven3 and Docker installed
    agent any
   
   tools { 
        maven 'MAVEN3' 
    }

    triggers {
        pollSCM 'H H 1 12 *'
    }

    stages {

        stage ('Checkout source code') {
            steps {
                git branch: 'master',
                    url: "${repo_url}"
            }
        }

        stage ('Build app') {
            steps {
                   sh '''
                   pwd
                   mvn clean package -DskipTests=true
                   '''
            }
        }

        stage ('Run unit tests') {
            steps {
                    sh "mvn test"
            }
        }
    }


    post {
        always {
            cleanWs()
        }
    }
}


