apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentapi
  template:
    metadata:
      labels:
        app: studentapi
    spec:
      containers:
        - name: studentapi
          image: mahesh1985/student-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "test"


---
apiVersion: v1
kind: Service
metadata:
  name: studentapi
spec:
  type: NodePort
  selector:
    app: studentapi
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
